### PR TITLE
Add a deprecation notice

### PR DESCRIPTION
**Pull request by camfindlay**
Inform users of this module to instead use https://github.com/silverstripe/recipe-reporting-tools

Sound ok @jvdanker @wilr

### CODE REVIEW

**Comment by wilr** [comment]
@camfindlay sounds good. You can also mark the repo as archived via `Settings` in Github which displays a warning on all the pages.

**Comment by camfindlay** [comment]
Was this also added to packagist? You can add metadata there too to suggest the other module I think.

**Comment by camfindlay** [comment]
Actually you can only provide a `suggest` - better than nothing - I'll add.

**Comment by camfindlay** [comment]
@wilr howzat?! :D

**Pull request merged**
